DROP DATABASE IF EXISTS game;
CREATE DATABASE game;

\c game;

CREATE TABLE scores(
  id INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(10) NOT NULL DEFAULT 'Anonymous' PRIMARY KEY,
    score INT(5) UNSIGNED NOT NULL DEFAULT '0',
    ts TIMESTAMP NOT NULL DEFAULT GETDATE()
)

INSERT INTO scores (name, score)
  VALUES ('Nick', 15);
